from hydro.models.requirement import *
from hydro.models.qualification import *
from hydro.models.qualification_entrance_requirement_subject import *
from hydro.models.campus import *
from hydro.models.provider import *
from hydro.models.occupation import *
from hydro.models.field_of_study import *
from hydro.models.sub_field_of_study import *
from hydro.models.subject import *
from hydro.models.module import *
from hydro.models.secondary_institution_type import *
